# -*- coding: utf-8 -*-
"""PythonInterview.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bomXIqWosS2HR4HHI2z6WlS5DESIfXan

***Interview Questions***

1.	What are the data types in python?

  Datatypes in Python are:
-	List  # [1,2,3,’a’,’b’]
-	Tuple # (1,2,3,’a’,’b’)
-	int # 12, 56
-	float # 17.89,45.789
-	set # {1,2,3,89,56}
-	dict # {‘key’: ’value’}
-	bool # True, False

2.	What is the diff b/w list and tuple?

Difference between list and tuple:
List =>
Lists are defined as []	Lists can be updated even after defining the list i.e., Mutable
List have more methods that we can do more functionality over the list or list elements
Tuple =>
Tuples are defined as () Tuples can’t be updated after declaration i.e., Immutable
Tuples have two methods (index, count) as they are immutable datatypes.

3.	String slicing
str1="this is python"
str1[1:--4] = ?
str1[-2:1] = ?
"""

str1="this is python"
str1[1:-4]

str1[-2:1]

#Merge 2 dictionaries
x = {1:22, 3:44, 5:66}
y = {'a': 'b', 'c': 'd'}
x.update(y)
print(x)

#5.	What is the difference b/w append and extend?
#	append is used to add a single value at the end of the list.

x = [1, 2, 3, 4, 5]
x.append('g')
print(x) # [1, 2, 3, 4, 5, ’g’]

#	extend is used to add multiple values at a time as iterator.
x = [1, 2, 3, 4, 5]
x.extend('ghi')
print(x) # [1, 2, 3, 4, 5, ’g’, ’h’, ’i’]

"""6.	What is the use of with keyword in files?

    ‘with’ keyword is used in file handling that will help  to close the file automatically once opened.

    Ex: with open(“filename.txt”,r) as fr:
		fr.readline()

7.	What is ZIP function write one example?

		Zip function maps the similar indexed values of multiple containers.

  Syntax: zip(*iterables)
"""

num = [15, 20, 30, 33, 60]
marks = [ 44, 56, 76, 97, 60]
print(set(zip(num, marks))) # {(15, 44), (30, 76), (20, 56), (60, 60), (33, 97)}

"""8.	What is List Comprehension?

	List comprehension is an elegant way to define and create lists based on existing lists.
	List comprehension is generally more compact and faster than normal functions and loops for creating list.

 Syntax: [expression for item in iterable]

"""

print([i*2 for i in 'praveen'])

"""9.	What is Dict Comprehension?

  List comprehension idea is carried over in defining dict   comprehension as well. Dict comprehension is defined with a similar syntax, but with a key: value pair in expression.

	Syntax: {key: value for object in iterable}

"""

Names = ['Praveen', 'Siva', 'Chakri', 'Sriram']
{n: len(n) for n in Names}

"""10.	What is lambda function write one example?

	Lambda functions also called as Anonymous functions or nameless functions.
	These functions will be used for containing functionality that need for short- term use.

  Syntax:  lambda expression

"""

y = lambda x: x//2
print(y(10))

"""Thanks For Watching File link is available in description"""

